const disease_arr = ['Abnormal uterine bleeding',
'Acquired Capillary Haemangioma of Eyelid',
'Acquired Immuno Deficiency Syndrome',
'Acute encephalitis syndrome', 'Adult Inclusion Conjunctivitis',
'Alcohol Abuse and Alcoholism', 'Alopecia (hair loss)',
"Alzheimer's Disease", 'Amaurosis Fugax', 'Amblyopia',
'Amoebiasis', 'Anaemia', 'Aniseikonia', 'Anisometropia', 'Anthrax',
'Anxiety', 'Appendicitis', 'Arthritis',
'Asbestos-related diseases', 'Asthma', 'Astigmatism', 'Autism',
'Bad Breath (Halitosis)', "Bell's Palsy", 'Blepharitis',
'Blindness', 'Brain Tumour', 'Breast Cancer / Carcinoma',
'Bronchitis', 'Brucellosis', 'Burns', 'Cancer',
'Carpal Tunnel Syndrome', 'Cavities', 'Chalazion', 'Chickenpox',
'Chikungunya Fever', 'Childhood Exotropia', 'Cholera',
'Chronic obstructive pulmonary disease (COPD)',
'Cleft Lip and Cleft Palate', 'Colorectal Cancer',
'Congenital anomalies (birth defects)', 'Corneal Abrasion',
'Coronary Heart Disease', 'Coronavirus disease 2019 (COVID-19)',
'Cough', 'Crimean-Congo haemorrhagic fever (CCHF)', 'Deafness',
'Dementia', 'Dengue Fever', 'Diabetes Mellitus',
'Diabetic Retinopathy', 'Diarrhea', 'Diphtheria',
"Down's Syndrome", 'Dracunculiasis (guinea-worm disease)',
'Early pregnancy loss', 'Ebola Virus Disease (EVD)', 'Eclampsia',
'Ectopic pregnancy', 'Eczema', 'Endometriosis', 'Epilepsy',
'Exposure Keratopathy', 'Factitious Keratoconjunctivitis',
'Fibroids', 'Fibromyalgia', 'Filamentary Keratitis', 'Filariasis',
"Frey's Syndrome", 'Frost Bite', 'Gaming disorder', 'Gangrene',
'Gastro-Esophageal Reflux Disease (GERD)', 'Glaucoma', 'Goitre',
'Gonorrhea', 'Guillain-Barré syndrome', 'Gum disease',
'Haemophilia', 'Hand, Foot and Mouth Disease',
'Heat-Related Illnesses and Heat waves', 'Hepatitis',
'Herpes Simplex', 'High risk pregnancy', 'Hypermetropia',
'Inflammatory Bowel Disease', 'Insomnia', 'Iron Deficiency Anemia',
'Japanese Encephalitis', 'Jaundice', 'Kala-azar/ Leishmaniasis',
'Kaposi’s Sarcoma',
'Keratoconjunctivitis Sicca (Dry eye syndrome)', 'Keratoconus',
'Lead poisoning', 'Leprosy', 'Leptospirosis', 'Leukemia',
'Lymphoedema', 'Malaria', 'Mastitis', 'Measles(Khasra)',
'Meningitis', 'Microcephaly',
'Middle East respiratory syndrome coronavirus (MERS‐CoV)',
'Migraine', 'Mouth Breathing', 'Mucormycosis', 'Mumps',
'Myocardial Infarction (Heart Attack)', 'Myopia', 'Narcolepsy',
'Nasal Polyps',
'Nausea and Vomiting of Pregnancy and  Hyperemesis gravidarum',
'Nipah virus infection', 'Nonalcoholic fatty liver disease(NAFLD)',
'Obesity', 'Obsessive Compulsive Disorder', 'Oral Cancer',
'Orbital Dermoid', 'Osteoarthritis', 'Osteomyelitis',
'Osteoporosis', 'Otitis Media', "Parkinson's Disease",
'Pellucid Marginal Degeneration', 'Pericarditis', 'Plague',
'Pneumonia', 'Poliomyelitis', 'Polycystic ovary syndrome (PCOS)',
'Post-herpetic neuralgia',
'Postpartum depression/ Perinatal depression',
'Postpartum haemorrhage', 'Preeclampsia', 'Premenstrual syndrome',
'Presbyopia', 'Preterm birth', 'Psoriasis', 'Pterygium',
'Puerperal sepsis', 'Quinsy', 'Rabies', "Raynaud's Phenomenon",
'Rheumatic fever and rheumatic heart disease', 'Rubella',
'Sarcoidosis', 'Sarcoma', 'Scabies', 'Schizophrenia',
'Scrub Typhus', 'Scurvy',
'Severe Acute Respiratory Syndrome (SARS)',
'Sexually transmitted infections (STIs)', 'Shaken Baby Syndrome',
'Stroke', 'Sub-conjunctival Haemorrhage', 'Substance abuse',
'Superior Limbic Keratoconjunctivitis', 'Syphilis',
'Taeniasis/cysticercosis', 'Tetanus', 'Thalassaemia', 'Trachoma',
'Tuberculosis', 'Turners Syndrome', 'Typhoid / Enteric Fever',
'Ulcerative Colitis', 'Urticaria', 'Varicose Veins',
'Vitamin B12 Deficiency', 'Vitiligo', 'Xerophthalmia', 'Yaws',
'Yellow Fever', 'lactose intolerance']

module.exports = {disease_arr}