const symptom_arr = ['abdominal pain',
'abnormal bleeding',
'abnormal sensation',
'abnormally frequent',
'abnormally small head brain',
'abscess',
'acne',
'acquiring drinking alcohol taking lot time',
'affected part turning white',
'anemia',
'anxiety',
'arm',
'asthenopia',
'asymptomatic',
'back',
'bad breath',
'bad smelling vaginal discharge',
'barking cough',
'better sitting worse lying',
'birth baby younger week gestational age',
'black area skin',
'bleeding',
'bleeding gum',
'bleeding skin',
'blindness',
'blister break open form small ulcer',
'bloating',
'blood stool',
'bloody diarrhea',
'blue',
'blurred vision',
'blurry vision',
'breast',
'breathing problem',
'bruising',
'burning',
'burning sensation',
'burning stabbing pain',
'burning urination',
'case asymptomatic',
'certain thought repeatedly',
'change bowel movement',
'change breast shape',
'change hair',
'change reflex',
'change skin color red black',
'change sleeping eating pattern',
'change taste',
'change time',
'change voice',
'characteristic facial feature',
'chest discomfort',
'chest pain',
'chest tightness',
'chill',
'chronic cough',
'chronic fatigue',
'close object appear normal',
'clumsiness',
'cm lump skin',
'cold sweat',
'coma',
'confused thinking',
'confusion',
'constipation',
'coolness',
'corneal ulceration',
'cough',
'cough bloody mucus',
'coughing',
'coughing mucus',
'cramp',
'crusty eyelid',
'cry episode',
'dark urine',
'darker',
'daytime sleepiness',
'decreased ability feel pain',
'decreased ability hear',
'decreased ability see',
'decreased ability think',
'decreased ability think remember',
'decreased appetite',
'decreased motivation',
'decreased range motion',
'decreased taste',
'decreased vision',
'dehydration',
'delayed physical growth',
'delusion',
'depends location runny nose',
'depends organ involved',
'depressed mood',
'depression',
'developmental disability',
'diarrhea',
'diarrhea constipation',
'diarrhea mixed blood',
'diarrhoea',
'diarrhoea may bloody',
'difficulty breathing',
'difficulty cutting',
'difficulty eating',
'difficulty getting pregnant',
'difficulty reading small print',
'difficulty remembering recent event',
'difficulty socializing others',
'difficulty swallowing',
'difficulty walking',
'dimpling skin',
'discharge',
'discharge penis',
'disorientation',
'distance near blur',
'distant object appear blurry',
'distorted blurred vision distance',
'dizziness',
'drinking large amount alcohol long period',
'dry cough',
'dry damp skin',
'dry eye',
'dry mouth',
'dryness',
'ear pain',
'easy bleeding',
'easy prolonged bleeding',
'emotional problem',
'enlarged liver',
'enlarged spleen',
'enlarged thyroid',
'erythema',
'erythema marginatum',
'excess hair',
'excessive amount uterine bleeding',
'excessive daytime sleepiness',
'excessive salivation',
'extreme sadness',
'eye discharge',
'eye pain',
'eye pain photophobia',
'eye redness',
'eye strain',
'eyestrain',
'facial swelling',
'fast heartbeat',
'fatigue',
'fear water',
'feel need check thing repeatedly',
'feeling cold',
'feeling faint',
'feeling faint upon standing',
'feeling inferiority',
'feeling like passing',
'feeling tired',
'fever',
'fever start low increase daily',
'firm',
'firmly attached white patch mucous membrane',
'flat discolored spot bump may blister',
'flatulence',
'flu like illness',
'fluid nipple',
'frequent urination',
'fullness',
'genitals',
'gum disease',
'half ring finger',
'hallucination',
'hallucination usually hearing voice',
'hard swelling skin',
'headache',
'hearing loss',
'heartburn',
'heavy period',
'high blood pressure',
'high body temperature',
'hoarse voice',
'hold reading material farther away',
'hunger',
'hypervigilance',
'inability child',
'inability move facial muscle one side',
'inability move feel one side body',
'increased breath rate',
'increased fat',
'increased heart rate',
'increased hunger',
'increased risk broken bone',
'increased risk infection',
'increased thirst',
'index',
'infertility',
'inflamed eye',
'insomnia',
'intellectual disability',
'involuntary muscle movement',
'involuntary sleep episode',
'irregular',
'irregular menstrual period',
'irritability',
'irritation',
'itchiness',
'itchy',
'itchy blister',
'itchy bump',
'jaw',
'joint bone pain',
'joint pain',
'joint swelling',
'large amount watery diarrhea',
'leg',
'legal problem',
'light sensitivity',
'limited range motion ankle',
'little pain',
'liver dysfunction',
'localized breast pain redness',
'loose frequent bowel movement',
'loose teeth',
'loss appetite',
'loss appetite weight loss',
'loss hair part head body',
'loss smell',
'loss taste smell',
'loss vision one side',
'low energy',
'low red blood cell',
'low self esteem',
'lower abdominal pain',
'lump',
'lump breast',
'lump bump neck',
'malaise',
'may symptom',
'memory problem',
'mental change',
'mid dilated pupil',
'middle finger',
'mild moderate intellectual disability',
'minimal',
'missed period',
'mood change',
'mood swing',
'multiple painful joint',
'muscle ache',
'muscle cramp',
'muscle joint pain',
'muscle pain',
'muscle spasm',
'muscle weakness',
'muscle weakness beginning foot hand',
'muscle weakness resulting inability move',
'muscular pain',
'nausea',
'nausea vomiting',
'nausea vomiting weight loss dehydration occur',
'near blur',
'nearly undetectable spell',
'nearsightedness',
'neck',
'neck stiffness',
'neurological impairment',
'newly inverted nipple',
'night blindness',
'non itchy skin ulcer',
'non painful cyst middle eyelid',
'nonaligned eye',
'numbness',
'object different size eye',
'one eye myopia eye hyperopia',
'opening upper lip may extend nose palate',
'overlying redness',
'pain',
'pain area',
'pain around ear',
'pain doesnt end shingle subsides',
'pain specific bone',
'painful',
'painful blister white worm crawl',
'painful heavy period',
'painless',
'painless lump',
'pale color',
'pale skin',
'pallor',
'paralysis',
'paranoia',
'parotitis non specific symptom fever',
'patch thick',
'patch white skin',
'pelvic pain',
'penile discharge',
'perform certain routine repeatedly',
'period vigorous shaking',
'persistent dry cough',
'persistent rough white red patch mouth lasting longer week',
'photophobia',
'physical disability',
'pimple like rash',
'pinkish',
'playing video game extremely long period time',
'poor appetite',
'poor tolerance heat',
'possibly reaching high f c headache',
'post nasal drip',
'presence anemia',
'presence restricted interest repetitive behavior',
'problem gambling',
'problem language',
'problem understanding speaking',
'problem vision',
'problem work school',
'prolonged',
'prolonged cough',
'protein urine',
'purple colored skin lesion',
'raised',
'raised red blue lesion',
'rapid breathing',
'rash',
'recurring episode wheezing',
'red',
'red eye',
'red purple darker skin',
'red scaly patch skin breast',
'red skin',
'red spot white eye',
'red without blister',
'reddish eye',
'redness',
'redness eye',
'redness sweating cheek area salivating',
'relationship difficulty',
'right lower abdominal pain',
'rigidity',
'runny nose',
'scaly patch skin',
'scratchiness',
'seizure',
'sensitivity light',
'sensitivity smell',
'sensitivity sound',
'severe swelling arm',
'sharp chest pain',
'short stature',
'shortness breath',
'significant blood loss childbirth',
'skin breakdown',
'skin ulcer',
'sleep problem',
'sleeping problem',
'slowness movement',
'small',
'small blister surrounding swelling',
'snoring',
'social isolation',
'social withdrawal',
'sore arm leg',
'sore throat',
'stiff neck',
'stiffness',
'stomach pain',
'sudden loss muscle strength',
'sweating',
'swell pain near tumor',
'swelling',
'swollen',
'swollen hand foot',
'swollen lymph node',
'swollen stomach enlarged liver spleen',
'taste acid',
'tearing',
'temporary fleeting vision one eye',
'tender breast',
'tenderness',
'testicular pain',
'throat pain',
'tingling hand foot',
'tingling thumb',
'tiredness',
'tooth loss',
'tremor',
'triangular tissue growth cornea',
'trouble breathing nose',
'trouble opening mouth',
'trouble sleeping',
'trouble social interaction',
'ulcer',
'ulcer around genitals',
'ulceration',
'unexplained weight loss',
'unpleasant smell present breath',
'usage resulting problem',
'usually ascending',
'vaginal bleeding',
'vaginal bleeding without pain',
'vaginal discharge',
'variable',
'vary depending part brain involved',
'velvety skin',
'verbal nonverbal communication',
'vision loss',
'vomiting',
'vomiting blood',
'weak grip',
'weakness',
'weakness fatigue',
'webbed neck',
'weight loss',
'wheezing',
'widespread pain',
'withdrawal occurring stopping',
'yellow skin',
'yellowish coloration skin white eye',
'yellowish skin']

module.exports = {symptom_arr}